[package]
name = "ray-casting-prototype"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytemuck = { version = "1.18.0", features = ["derive"] }
image = "0.25.2"
pollster = "0.3.0"
wgpu = "22.1.0"
winit = { version = "0.30.5", features = ["rwh_06"] }
